# Excluir regla 10004 para el viewer.html de Hypothesis
SecRule REQUEST_URI "@beginsWith /plugins/generic/pdfJsViewer/pdf.js/web/viewer.html" \
    "id:900001,phase:1,nolog,pass,ctl:ruleRemoveById=10004"
