# Bloquear archivos subidos con extensión PHP, PHAR, PHTML, etc.
SecRule FILES_NAMES "@rx \.(php|php[0-9]?|phtml|phar)$" \
    "id:10001,phase:2,deny,status:403,msg:'Intento de carga de archivo PHP malicioso'"

# Detectar contenido de código PHP dentro de los archivos
SecRule REQUEST_BODY "@rx <\?php" \
    "id:10002,phase:2,deny,status:403,msg:'Posible código PHP dentro de archivo subido',t:none"


# Prevenir RFI/LFI (inclusión de archivos remotos o locales)
SecRule REQUEST_URI "@rx (\.\./|\.\.\\|/etc/passwd|/proc/)" \
    "id:10003,phase:2,deny,status:403,msg:'Intento de LFI/RFI detectado'"

# Bloqueo de accesos sospechosos a rutas de OJS
SecRule REQUEST_URI "@rx (\/plugins\/.*\.php|\/cache\/.*\.php)" \
    "id:10004,phase:2,deny,status:403,msg:'Intento de acceso directo a PHP en OJS'"

# Prevenir SQL injection simple
SecRule ARGS "(union select|sleep\(|benchmark\(|information_schema)" \
    "id:10005,phase:2,deny,status:403,msg:'Intento de SQL Injection'"

# Prevenir XSS básico
SecRule ARGS "<script|onerror=|onload=|alert\(" \
    "id:10006,phase:2,deny,status:403,msg:'Intento de XSS detectado'"

# ==============================
# 7.
# Bloquear redirecciones no permitidas para el endpoint /index.php/path/login/signOut
# ==============================
SecRule REQUEST_URI "@rx ^/index\.php/[^/]+/login/signOut(?:\?|$)" \
    "id:10007,phase:2,chain,deny,status:403,rev:3,msg:'Open Redirect attempt in signOut via source'"
    SecRule ARGS:source "!@rx ^/[A-Za-z0-9/_-]*$"

# Bloquear acceso a manuales de ayuda (son considerados huecos de seguridad)
SecRule REQUEST_URI "@rx ^/index\.php/[^/]+/help/" \
    "id:10008,phase:1,deny,status:403,msg:'Bloqueo de rutas help de OJS'"

# Bloquear setLocale por path exacto
#SecRule REQUEST_URI "@rx ^/index\.php/[^/]+/user/setLocale/(en|es|pt_BR)$" \
#    "id:10009,phase:1,deny,log,auditlog,msg:'Blocked suspicious setLocale path - possible open redirect',severity:2"

# Bloquear Referer externo sobre los recursos /index.php/path/user/setLocale/en
SecRule REQUEST_URI "@rx ^/index\.php/[^/]+/user/setLocale/(en|es|pt_BR)$" \
    "id:10010,phase:2,chain,deny,status:403,msg:'Open Redirect attempt via Referer in setLocale'"
    SecRule REQUEST_HEADERS:Referer "@rx ^(https?://|//|\.)" "t:lowercase"
